export * as basicLayout from './basic-layout.html?raw'
export * as header from './header.html?raw'
export * as footer from './footer.html?raw'
export * as rupteur from './rupteur.html?raw'
export * as returnButton from './returnButton.html?raw'
export * as tabs from './tabs.html?raw'
